source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftChatKit_Example', :exclusive => true do
  pod "SwiftChatKit", :path => "../"
  #环信即时通讯SDK
  pod 'EaseMobSDK'
end

target 'SwiftChatKit_Tests', :exclusive => true do
  pod "SwiftChatKit", :path => "../"
end
